spring:
  application:
    name: eureka-server
  cloud:
    discovery:
      client:
        simple:
          local:
            uri: localhost

server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
    # 由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例, 它并不需要去检索服务, 所以也设置为 false
    fetch-registry: false
  server:
    # 自我保护
    enableSelfPreservation: false
  instance:
    # 采用IP注册
    preferIpAddress: true
    # 定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.discovery.client.simple.local.uri}:${server.port}
