spring:
  application:
    name: config-server
  cloud:
    discovery:
      client:
        simple:
          local:
            uri: localhost
    config:
      server:
        git:
          uri: https://github.com/lvyang0704/SpringCloudLearning/
          search-paths: config_server/config-repo
          username: 1092339490@qq.com
          password: 0904221x
server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    # 采用IP注册
    preferIpAddress: true
    # 定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.discovery.client.simple.local.uri}:${server.port}
